/**
 * fix_session_times.mjs
 *
 * Reads Data/schedule_times.xlsx (generated by parse_schedules.mjs)
 * and updates session start_time + end_time in the DB.
 *
 * SAFE: Only updates start_time/end_time — zero deletions, attendance untouched.
 *
 * Usage:
 *   cd client-next
 *   node scripts/fix_session_times.mjs
 */

import { createClient } from '@supabase/supabase-js';
import xlsx from 'xlsx';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

<<<<<<< HEAD
const SUPABASE_URL         = process.env.SUPABASE_URL || 'https://pvqxzbabstyhskhydbvl.supabase.co';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;
if (!SUPABASE_SERVICE_KEY) throw new Error('SUPABASE_SERVICE_KEY env var is not set. Add it to .env before running.');
=======
const SUPABASE_URL         = 'https://pvqxzbabstyhskhydbvl.supabase.co';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
>>>>>>> 7658f2ac563b0494eb5d492cf1cc267b94a33e63

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

const SCHEDULE_FILE = path.resolve(__dirname, '../../Data/schedule_times.xlsx');

function pad(n) { return String(n).padStart(2, '0'); }

async function main() {
  console.log('\n================================================');
  console.log('  Fix Session Times — Safe DB Update');
  console.log('================================================\n');

  // ── Load schedule Excel ────────────────────────────────────────────────────
  const wb   = xlsx.readFile(SCHEDULE_FILE);
  const rows = xlsx.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { defval: '' });
  console.log(`Loaded ${rows.length} schedule rows from Excel`);

  // Build a map: date → [ {start, end}, {start, end}, ... ] sorted by slot order
  const scheduleByDate = {};
  for (const row of rows) {
    const date = String(row.date || '').trim();
    if (!date || !date.match(/^\d{4}-\d{2}-\d{2}$/)) continue;

    const slots = [];
    for (let s = 1; s <= 4; s++) {
      const start = String(row[`slot${s}_start`] || '').trim();
      const end   = String(row[`slot${s}_end`]   || '').trim();
      if (start && end && start.match(/^\d{2}:\d{2}$/) && end.match(/^\d{2}:\d{2}$/)) {
        slots.push({ start, end });
      }
    }
    if (slots.length > 0) scheduleByDate[date] = slots;
  }

  const scheduleDates = Object.keys(scheduleByDate).sort();
  console.log(`Schedule covers ${scheduleDates.length} dates: ${scheduleDates[0]} → ${scheduleDates[scheduleDates.length-1]}\n`);

  // ── Fetch sessions for those dates ─────────────────────────────────────────
  const { data: sessions, error: sErr } = await supabase
    .from('sessions')
    .select('id, session_date, start_time, end_time, course_id, title')
    .in('session_date', scheduleDates)
    .order('session_date')
    .order('start_time');

  if (sErr) { console.error('Fetch sessions error:', sErr.message); process.exit(1); }
  console.log(`Found ${sessions.length} sessions in DB matching schedule dates`);

  // Group sessions by date, sorted by current start_time (slot order)
  const sessionsByDate = {};
  for (const s of sessions) {
    if (!sessionsByDate[s.session_date]) sessionsByDate[s.session_date] = [];
    sessionsByDate[s.session_date].push(s);
  }

  // ── Match and update ────────────────────────────────────────────────────────
  let updated = 0, skipped = 0, mismatched = 0;

  for (const date of scheduleDates) {
    const slots    = scheduleByDate[date];
    const dbSess   = (sessionsByDate[date] || []).sort((a, b) =>
      (a.start_time || '').localeCompare(b.start_time || '')
    );

    if (dbSess.length === 0) {
      console.log(`  ${date}: no sessions in DB — skip`);
      skipped++;
      continue;
    }

    if (dbSess.length !== slots.length) {
      console.log(`  ${date}: WARN — ${dbSess.length} sessions in DB but ${slots.length} slots in schedule`);
      // Still try to update as many as match
    }

    const count = Math.min(dbSess.length, slots.length);
    for (let i = 0; i < count; i++) {
      const sess = dbSess[i];
      const slot = slots[i];
      const newStart = slot.start + ':00'; // DB stores HH:MM:SS
      const newEnd   = slot.end   + ':00';

      const currentStart = (sess.start_time || '').slice(0, 5);
      const currentEnd   = (sess.end_time   || '').slice(0, 5);

      if (currentStart === slot.start && currentEnd === slot.end) {
        // Already correct — no update needed
        continue;
      }

      const { error: uErr } = await supabase
        .from('sessions')
        .update({ start_time: newStart, end_time: newEnd })
        .eq('id', sess.id);

      if (uErr) {
        console.log(`  ${date} slot${i+1}: ERROR — ${uErr.message}`);
        mismatched++;
      } else {
        console.log(`  ${date} slot${i+1}: ${currentStart}-${currentEnd.slice(0,5) || '?'} → ${slot.start}-${slot.end}  (${sess.title?.slice(0,40)})`);
        updated++;
      }
    }
  }

  // ── Summary ─────────────────────────────────────────────────────────────────
  console.log('\n================================================');
  console.log('  Update Complete — Attendance Monitoring Fixed');
  console.log('================================================');
  console.log(`  Sessions updated:  ${updated}`);
  console.log(`  Already correct:   ${sessions.length - updated - mismatched}`);
  console.log(`  Dates with no DB:  ${skipped}`);
  console.log(`  Errors:            ${mismatched}`);
  console.log('\n  Attendance records untouched.');
  console.log('  Visit /admin/attendance to verify timings.\n');
}

main().catch(e => { console.error('Fatal:', e.message); process.exit(1); });
